name: Publish AgentKit Plugin to PyPI

on:
  workflow_dispatch:

jobs:
  agentkit-plugin-pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packages/agentkit-plugin/python
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build
        run: poetry build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: packages/agentkit-plugin/python/dist/
