import {
  AgentRegistrationFile,
  Service,
  RegistrationEntry,
  TrustMechanism,
} from "@aixyz/erc-8004/schemas/registration";

/**
 * ERC-8004 Agent Registration File
 * Used for registering agents on the MCP and other ERC-8004 compliant platforms
 */
export type ERC8004Registration = Omit<
  AgentRegistrationFile,
  "type" | "name" | "description" | "image" | "services" | "registrations" | "supportedTrust" | "active" | "x402support"
> & {
  /**
   * Defaults to `"https://eips.ethereum.org/EIPS/eip-8004#registration-v1"` if not specified.
   */
  type?: "https://eips.ethereum.org/EIPS/eip-8004#registration-v1";
  /**
   * Defaults to `aixyz.config.ts`.`name`.
   */
  name?: string;
  /**
   * Defaults to `aixyz.config.ts`.`description`.
   */
  description?: string;
  /**
   * Defaults to `aixyz.config.ts`.`url` + `/icon.png`.
   */
  image?: string;
  /**
   * Array of service endpoints. Examples: MCP server, A2A endpoint, web interface, OASF spec.
   * Automatically generated by the CLI if not specified.
   */
  services?: Service[];
  /**
   * Registration entry, also links to agent registrations on other chains
   * Format: { agentId: "123", agentRegistry: "eip155:1:0x..." }
   * Will be automatically be populated during `aixyz erc-8004 register`
   */
  registrations?: RegistrationEntry[];
  /**
   * Defaults to `aixyz.config.ts`.`supportedTrust`.
   */
  supportedTrust?: TrustMechanism[];
  /**
   * Defaults to `true`.
   */
  active?: boolean;
  /**
   * Defaults to `true`.
   */
  x402support?: boolean;
};
