name: "Free Crypto News"
description: "Real-time crypto news API with MCP server for AI agents. RSS feeds, REST API, historical archive. SDKs for Python, TypeScript, Go, React. No API key required."
url: "https://github.com/nirholas/free-crypto-news"
docs: "https://github.com/nirholas/free-crypto-news/blob/main/docs/openrouter.md"
tags:
  - research
  - productivity
open_source: "https://github.com/nirholas/free-crypto-news"
date_added: "2026-01-28"
