name: "AI Agents Library"
description: "Comprehensive collection of specialized AI agents with universal compatibility. Works with any AI platform supporting agent indexes. No vendor lock-in."
url: "https://github.com/nirholas/AI-Agents-Library"
docs: "https://github.com/nirholas/AI-Agents-Library#readme"
tags:
  - coding
open_source: "https://github.com/nirholas/AI-Agents-Library"
date_added: "2026-01-28"
