name: "Universal Crypto MCP"
description: "Universal MCP server for AI agents to interact with any blockchain. Supports swaps, bridges, staking, lending across Ethereum, Arbitrum, Base, Polygon, BSC."
url: "https://github.com/nirholas/universal-crypto-mcp"
docs: "https://github.com/nirholas/universal-crypto-mcp/blob/main/docs/openrouter.md"
tags:
  - coding
  - productivity
open_source: "https://github.com/nirholas/universal-crypto-mcp"
date_added: "2026-01-28"
