import type { BlockConfig } from '../types.js'

export const AgentiSolanaBlock: BlockConfig = {
  type: 'agenti_solana',
  name: 'Agenti Solana Trading',
  description: 'Trade Solana tokens on pump.fun and Raydium. Analyze smart wallets, get token prices, and execute buy/sell operations with automatic routing.',
  category: 'tools',
  bgColor: '#b45309',
  tags: ['crypto', 'solana', 'trading', 'pump.fun', 'defi'],
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      options: [
        { label: 'Get Token Price', value: 'price' },
        { label: 'Buy Token', value: 'buy' },
        { label: 'Sell Token', value: 'sell' },
        { label: 'Analyze Smart Wallet', value: 'smart-wallet' },
      ],
    },
    {
      id: 'mint',
      title: 'Token Mint Address',
      type: 'short-input',
      required: { field: 'operation', value: ['price', 'buy', 'sell'] },
      condition: { field: 'operation', value: ['price', 'buy', 'sell'] },
      placeholder: 'Base58 mint address',
    },
    {
      id: 'solAmount',
      title: 'SOL Amount',
      type: 'short-input',
      required: { field: 'operation', value: 'buy' },
      condition: { field: 'operation', value: 'buy' },
      placeholder: '0.1',
    },
    {
      id: 'tokenAmount',
      title: 'Token Amount',
      type: 'short-input',
      required: { field: 'operation', value: 'sell' },
      condition: { field: 'operation', value: 'sell' },
      placeholder: 'e.g. 1000000 or "all"',
    },
    {
      id: 'slippageBps',
      title: 'Slippage (bps)',
      type: 'short-input',
      required: false,
      condition: { field: 'operation', value: ['buy', 'sell'] },
      defaultValue: 100,
      placeholder: '100 = 1%',
    },
    {
      id: 'walletAddress',
      title: 'Wallet Address',
      type: 'short-input',
      required: { field: 'operation', value: 'smart-wallet' },
      condition: { field: 'operation', value: 'smart-wallet' },
      placeholder: 'Solana wallet to analyze',
    },
    {
      id: 'solanaPrivateKey',
      title: 'Solana Private Key',
      type: 'short-input',
      required: { field: 'operation', value: ['buy', 'sell'] },
      condition: { field: 'operation', value: ['buy', 'sell'] },
      placeholder: 'Base58 private key',
    },
    {
      id: 'serverUrl',
      title: 'Bridge Server URL',
      type: 'short-input',
      required: false,
      defaultValue: 'http://localhost:3200',
      placeholder: 'http://localhost:3200',
    },
  ],
  tools: {
    access: [
      'agenti_solana_token_price',
      'agenti_solana_buy',
      'agenti_solana_sell',
      'agenti_smart_wallet',
    ],
    config: {
      tool: (params) => {
        const map: Record<string, string> = {
          price: 'agenti_solana_token_price',
          buy: 'agenti_solana_buy',
          sell: 'agenti_solana_sell',
          'smart-wallet': 'agenti_smart_wallet',
        }
        return map[params.operation as string] ?? 'agenti_solana_token_price'
      },
      params: (params) => ({
        mint: params.mint,
        solAmount: params.solAmount ? Number(params.solAmount) : undefined,
        tokenAmount: params.tokenAmount,
        slippageBps: params.slippageBps ? Number(params.slippageBps) : 100,
        walletAddress: params.walletAddress,
        solanaPrivateKey: params.solanaPrivateKey,
        serverUrl: params.serverUrl,
      }),
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Solana operation' },
    mint: { type: 'string', description: 'Token mint address' },
    solAmount: { type: 'number', description: 'SOL amount to spend' },
    tokenAmount: { type: 'string', description: 'Token amount to sell' },
    slippageBps: { type: 'number', description: 'Slippage basis points' },
    walletAddress: { type: 'string', description: 'Wallet to analyze' },
    solanaPrivateKey: { type: 'string', description: 'Signing key' },
    serverUrl: { type: 'string', description: 'Bridge server URL' },
  },
  outputs: {
    price: { type: 'number', description: 'Token price in SOL' },
    priceUsd: { type: 'number', description: 'Token price in USD' },
    txHash: { type: 'string', description: 'Transaction signature' },
    solSpent: { type: 'number', description: 'SOL spent (buy)' },
    solReceived: { type: 'number', description: 'SOL received (sell)' },
    tokensReceived: { type: 'string', description: 'Tokens received (buy)' },
    tokensSold: { type: 'string', description: 'Tokens sold (sell)' },
    isSmart: { type: 'boolean', description: 'Smart wallet classification' },
    winRate: { type: 'number', description: 'Wallet win rate %' },
    recentTrades: { type: 'json', description: 'Recent trade history' },
  },
}
