name: "Agenti"
description: "Universal MCP server for blockchain and DeFi. 380+ tools across 20+ chains. AI agents can swap, stake, bridge, check security, and pay for APIs via x402."
url: "https://github.com/nirholas/agenti"
docs: "https://github.com/nirholas/agenti/blob/main/docs/content/openrouter.md"
tags:
  - coding
  - productivity
open_source: "https://github.com/nirholas/agenti"
date_added: "2026-01-28"
