#!/bin/bash

# ChaosChain x402 Facilitator Demo - Environment Setup Script

echo "🔧 Setting up environment for ChaosChain x402 demo..."
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file"
        exit 0
    fi
fi

# Create .env file
cat > .env << 'EOF'
# ChaosChain x402 Facilitator Demo - Environment Variables
# Generated by setup_env.sh

# ============================================
# x402 Facilitator Configuration
# ============================================
X402_FACILITATOR_URL=http://localhost:8402

# ============================================
# RPC Endpoints
# ============================================
# Using free public RPC (may be rate-limited)
BASE_SEPOLIA_RPC_URL=https://sepolia.base.org

# ============================================
# Demo Mode
# ============================================
# Set to 'true' to skip SDK initialization (uses mock agent)
DEMO_MODE_NO_SDK=false
EOF

echo "✅ Created .env file with default values"
echo ""
echo "📝 Next steps:"
echo ""
echo "1. (Optional) Get a free RPC API key:"
echo "   • Alchemy: https://www.alchemy.com"
echo "   • Infura: https://www.infura.io"
echo "   • QuickNode: https://www.quicknode.com"
echo ""
echo "2. (Optional) Update .env with your API key:"
echo "   BASE_SEPOLIA_RPC_URL=https://base-sepolia.g.alchemy.com/v2/YOUR_KEY"
echo ""
echo "3. Or run without SDK (mock agent mode):"
echo "   export DEMO_MODE_NO_SDK=true"
echo ""
echo "4. Start the facilitator:"
echo "   cd ../../http-bridge && npm run dev"
echo "   (or use Docker: docker-compose up http-bridge)"
echo ""
echo "5. Run the demo:"
echo "   python demo_facilitator.py"
echo ""

