name: "UCAI"
description: "Universal Contract AI Interface - MCP server generator for smart contracts. Connect AI agents to Uniswap, Aave, ERC20, NFTs. ABI to MCP conversion."
url: "https://github.com/nirholas/UCAI"
docs: "https://github.com/nirholas/ucai/blob/main/docs/openrouter.md"
tags:
  - coding
open_source: "https://github.com/nirholas/UCAI"
date_added: "2026-01-28"
