name: "XActions"
description: "Complete X/Twitter automation toolkit with MCP server for AI agents. Scrapers, CLI, browser scripts. Auto follow, like, comment, analytics. No API fees, open source."
url: "https://github.com/nirholas/XActions"
docs: "https://github.com/nirholas/xactions/blob/main/docs/openrouter.md"
tags:
  - productivity
open_source: "https://github.com/nirholas/XActions"
date_added: "2026-01-28"
